flox/pkgdb

src/nix-state.cc
tests/pkgdb.cc
tests/registry.cc
tests/resolver.cc

In several instances `static_cast<std::size_t>( 1 );` was used for rvalues.
These have been changed to use the `std::size_t( 1 );` constructor.

perf: construct std::size_t directly

---

include/flox/pkgdb/pkg-query.hh
include/flox/resolver/params.hh
include/flox/resolver/state.hh
include/flox/search/params.hh
src/pkgdb/pkg-query.cc
src/resolver/params.cc
src/search/params.cc
tests/data/search/defaults.json
tests/data/search/doc-params.json
tests/data/search/params0.json
tests/data/search/params1.json
tests/pkgdb.cc
tests/search-params.cc
tests/search.bats

Instead of using matchStyle to determine the meaning of match, split the two possible use cases into partialMatch and pnameOrPkgAttrName.

feat: replace matchStyle with two match variables

---

docs/search.md
include/flox/pkgdb/params.hh
include/flox/pkgdb/pkg-query.hh
include/flox/pkgdb/read.hh
include/flox/resolver/params.hh
include/flox/resolver/state.hh
include/flox/search/params.hh
src/pkgdb/params.cc
src/pkgdb/pkg-query.cc
src/pkgdb/schemas.hh
src/resolver/params.cc
src/search/params.cc
tests/data/search/defaults.json
tests/data/search/doc-params.json
tests/data/search/params0.json
tests/data/search/params1.json
tests/pkgdb.cc
tests/search-params.cc
tests/search.bats

Modifies `getPackages` and `PkgDbQuery` to use `match` argument to match a calculated column `pkgAttrName`.
For `catalog` subtrees this is the _second to last member of an attribute path_, e.g. `["catalog", "x86_64-linux", "stable", "hello", "latest"] => "hello"`.
For `packages` and `legacyPackages` subtrees this is the _last member of an attribute path_, e.g. `["catalog", "x86_64-linux", "hello"] => "hello"`.
Additionally this fixes a bug in the error output of `QueryPreferences` parsers which caused incorrect attribute paths like `allow.allow` and `semver.semver` to be emitted instead of `allow.bogus` and `semver.bogus`.

feat: match on pkgAttrName

---

include/flox/core/nix-state.hh
src/logger.cc
src/nix-state.cc

Adds a custom implementation of the `nix::Logger` interface, `flox::FilteredLogger`, which can ignore/suppress certain messages and control ANSI colors.
This replaces the default logger when `initNix()` is run ( at startup ).

feat: Add custom logger

---

include/flox/pkgdb/pkg-query.hh
src/pkgdb/pkg-query.cc
src/search/params.cc
tests/data/search/defaults.json
tests/data/search/doc-params.json
tests/data/search/params0.json
tests/data/search/params1.json
tests/search.bats

Restore `pkgdb search` parameter _name_ `query.match`.
When adding separate internal arguments for `partialMatch` and `pnameOrPkgAttrName` from the existing `match` argument, the _public interface_ was also renamed from `match` to `partialMatch`.
The _public interface_ change was unintended, and caused breakage in existing usage.

fix: revert renaming of query param 'match' -> 'partialMatch'

---

include/flox/core/util.hh
tests/util.cc

I swear that this is the upper limit of esoteric C++ templates you'll ever need to read in the code-base.
These are _magic_, but the code generation they provide is worth the boilerplate they eliminate <3
- Adds `to_json` and `from_json` conversion for STL `std::variant<...>` types.
- cleanup/doc for existing serializers.

feat: JSON ADL serializers for std::variant

---

tests/data/search/params-semver.json
tests/pkgdb.cc

I ran into some unexpected `semver` results using `flox::resolver::*` interfaces which are in development in a separate PR.
To sanity check the results I saw there I created a few new `semver` filtering tests for the `flox::pkgdb::PkgDbReadOnly::getPackage()` routine.
While filtering behaves _as specified_, I found that when searching/resolving across multiple inputs, the resulting order being _grouped by input_ may not be what is expected.

tests: additional semver filtering tests

---

.github/workflows/test.yml

Adds the use of _remote store_ binary caches to GitHub Actions.
This will improve performance in this repository and in `github:flox/flox`.

perf: use remote store caches in GitHub Actions

---

include/flox/core/util.hh
include/flox/pkgdb/pkg-query.hh
include/flox/resolver/descriptor.hh
include/versions.hh
src/resolver/descriptor.cc
src/util.cc
src/versions.cc
tests/data/manifest/manifest0.toml
tests/data/manifest/manifest0.yaml
tests/manifest.cc
tests/test.hh
tests/util.cc
tests/versions.cc

This covers parsing for manifest _descriptors_, being entries under `installs.<ID> = <DESCRIPTOR>`.

Parse Manifest Descriptor fields

---

include/flox/core/command.hh
src/command.cc
tests/data/registry/registry0.json
tests/registry.cc

This PR adds a `RegistryFileMixin` that adds the ability to load a `registry.json` file via path provided to `pkgdb`.

feat: add RegistryFileMixin

---

include/flox/registry.hh
tests/data/registry/registry1.json
tests/registry.cc

This PR disallows constructing a `Registry` from inputs that contain indirect flake references so that resolution is pure.

feat: no indirect flake refs

---

include/flox/pkgdb/input.hh
src/resolver/descriptor.cc

Remove unnecessary move:
src/resolver/descriptor.cc:52:24: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
desc.version = std::move( trimmed.substr( 1 ) );
^
src/resolver/descriptor.cc:52:24: note: remove std::move call here
desc.version = std::move( trimmed.substr( 1 ) );
^~~~~~~~~~~                    ~
Mark force unused:
include/flox/pkgdb/input.hh:251:10: warning: private field 'force' is not used [-Wunused-private-field]
bool force = false;  /**< Whether to force re-evaluation of flakes. */
^

fix: compiler warnings

---

include/flox/core/exceptions.hh
src/exceptions.cc
src/tomlToJSON.cc

FloxException will be used as the base class for all pkgdb exceptions, and they need to be able to be passed as JSON. The JSON output will be of the form:
{
"error_code": 102,
"category_message": "error converting TOML to JSON",
"context_message": "while parsing a TOML string",
"caught_message": "contents of e.what()"
}
Make the necessary changes to FloxException to store this information, and add a TOMLToJSONException to demonstrate how FloxException will be used as a base class.

feat: FloxException changes to enable JSON errors

---

Makefile

On mac, the command to generate CXX_SYSTEM_INCDIRS prints out the line: /nix/store/q2d0ya7rc5kmwbwvsqc2djvv88izn1q6-apple-framework-CoreFoundation-11.0.0/Library/Frameworks (framework directory) The '(framework directory)' then causes commands using CXX_SYSTEM_INCDIRS to fail with:
sh: -c: line 1: syntax error near unexpected token `('
Filter out that line since it's probably not frequently needed.

fix: make compile_commands.json on mac

---

include/flox/core/command.hh
include/flox/core/exceptions.hh
include/flox/flake-package.hh
include/flox/pkgdb/params.hh
include/flox/pkgdb/pkg-query.hh
include/flox/pkgdb/read.hh
include/flox/registry.hh
include/flox/resolver/descriptor.hh
include/flox/resolver/params.hh
include/flox/search/params.hh
src/command.cc
src/flake-package.cc
src/main.cc
src/pkgdb/command.cc
src/pkgdb/input.cc
src/pkgdb/params.cc
src/pkgdb/pkg-query.cc
src/pkgdb/read.cc
src/pkgdb/write.cc
src/resolver/descriptor.cc
src/resolver/params.cc
src/search/command.cc
src/search/params.cc
src/tomlToJSON.cc
src/yamlToJSON.cc
tests/.gitignore
tests/exceptions.cc
tests/pkgdb.cc

Having custom exceptions with their own error codes will allow better handling of errors when consuming pkgdb output from Rust.
Also remove dbPath from PkgDbException as it was not being used.

feat: replace FloxExceptions with custom ones

---

include/flox/core/exceptions.hh
src/exceptions.cc
src/main.cc
src/search/command.cc

* `main` now just invokes run and handles terminal exceptions.
* `FloxExceptions` can be formatted as json
* Error handling for search was dropped for the global error handling in `main`

refactor: split `main` method into `run` and error handling

---

flake.lock
flake.nix

Use `github:NixOS/nixpkgs/release-23.05` branch for `nixpkgs` input.
Make use of `nix@2.15` explicit in overlay.

follow nixpkgs/release-23.05

---

tests/pkgdb.cc
tests/registry.cc
tests/resolver.cc

Deletes some wonky separators in functions that `make fmt` indents and breaks over multiple lines.

style: drop separators from tests' main functions

---

include/flox/core/exceptions.hh
include/flox/flox-flake.hh
src/flox-flake.cc
src/main.cc
src/pkgdb/input.cc
src/registry.cc

- Add LockFlakeException to catch any exceptions thrown while calling nix::flake::lockFlake
- Add NixEvalException to catch nix::EvalError
- Catch any other nix::Error in main()
- Minor fix: use whatString instead of what for FloxException in main, as it will contain more information

feat: catch nix errors

---

pkg-fun.nix

Another option is to not use manual boost_CFLAGS, but this seems cleaner.
boost-dev becomes a part of the pc file:
```
lib/pkgconfig/flox-pkgdb.pc: …clude/nix/config.h -I/nix/store/1kprdajc7d9s1lvcn8vddqf4gvbp8cxw-boost-1.79.0-dev/include
```
Goal is to not include all of boost development in runtime closure. This is a 200MB difference in the closure size.

fix: use multiple outputs to isolate boost-dev

---

pkg-fun.nix

Making only nix to propagatedBuildInputs rather than nix.dev.

fix: remove nix.dev from runtime closure

---

Doxyfile
docs/params-to-sql.md
include/flox/core/exceptions.hh
include/flox/flake-package.hh
include/flox/flox-flake.hh
include/flox/pkgdb/input.hh
include/flox/pkgdb/params.hh
include/flox/pkgdb/pkg-query.hh
include/flox/resolver/descriptor.hh
include/flox/resolver/manifest.hh
include/flox/resolver/params.hh
include/flox/resolver/resolve.hh
src/command.cc
src/flake-package.cc
src/flox-flake.cc
src/logger.cc
src/nix-state.cc
src/pkgdb/input.cc
src/pkgdb/params.cc
src/pkgdb/pkg-query.cc
src/resolver/command.cc
src/yamlToJSON.cc

This document covers the various parameter parsers and structures that convert user input into SQL queries.
Largely it aims to be a guide for y'all to understand how those grew organically, and when some of them can be retired.
There's a few additions to inline docs as well in the related code.
You'll also notice some `#include` lines were modified - this was done programmatically by `include-what-you-use` ( which I don't have setup on my work machine ). It basically just drops `#include` lines that weren't in use, and explicitly adds ones that are used directly by a file but were supplied indirectly.
Finally I aligned the exceptions in `PkgQueryArgs` with the rest of the code-base.
I could split those into a separate PR but honestly it's just kind of a hassle to separate them and I'd …

doc: document query argument parsers

---

Makefile
include/flox/core/types.hh
include/flox/registry.hh
include/flox/resolver/descriptor.hh
include/flox/resolver/manifest.hh
include/flox/resolver/params.hh
include/flox/resolver/resolve.hh
src/pkgdb/input.cc
src/registry.cc
src/resolver/command.cc
src/resolver/descriptor.cc
src/resolver/manifest.cc
src/resolver/resolve.cc
tests/data/manifest/ga0.toml
tests/data/manifest/ga0.yaml
tests/manifest.cc
tests/registry.cc
tests/resolver-params.cc
tests/resolver.cc
tests/test.hh

This implements the simplest manifest -> lockfile strategy for descriptors.
It does not support `packageGroup` , multiple inputs, or `update` operations at this time - these features will be added in later tickets/PRs.
Currently the manifest file must contain a `registry` field; but a later PR will hard code `github:NixOS/nixpkgs/release-23.05` as the only available input.

feat: lock manifest descriptors ( no groups )

---

.github/workflows/test.yml

No longer needed since `merge_queue` runs make it redundant.

chore: skip GHA test runs on main

---

flake.lock
flake.nix
include/flox/core/nix-state.hh
include/flox/core/util.hh
nix-patches/multiple-github-tokens.2.13.2.patch
nix-patches/nix-9147.patch
pkg-fun.nix

brings Nix to 2.17
- brought in some patches to make nlohmann machinery work, ~~notably adding a variant<A,B,C> handler which is a bit ugly, but generic handling of arbitrary sum types in C++ is....... an exercise for the reader.~~ restored support for sum types
- included the multiple-github-tokens patch
- use overlays to make `nix` the patched version for all downstream users of the pkgdb overlays.

chore: update nix to 2.17

---

src/search/params.cc
src/versions.cc
tests/search.bats

- Fixes handling of semantic version __glob ranges_ such as `18*`, `18.*`, `18.x`, and `18.X`.
- Adds a new test case to ensure glob handling works.

fix: semver globs

---

include/flox/resolver/manifest.hh

An optional is being dereferenced even when it doesn't have a value. This appears to be causing the following behavior:
$ pkgdb manifest lock manifest.toml
vector
After this change, correct JSON is output.

fix: invalid optional dereference

---

src/pkgdb/schemas.hh
src/pkgdb/write.cc
tests/migrate.bats

When migrating _views schema_ all previously defined `VIEW`s are deleted and recreated.
Previously `VIEW`s were explicitly deleted by name, but if new `VIEW` definitions were added to the DB it was easy to forget to update the `PkgDb::updateViews()` routine.

fix: database views schema migration

---

include/flox/resolver/manifest.hh
src/resolver/environment.cc
src/resolver/manifest.cc

- docs: docstring and comment tweaks
Underlying code looks great.
For Doxygen docstrings `@brief` continuations have to be indendent, and for whatever reason if your block is multiple lines `/**` has to be _on its own_:
```c++
// Renders improperly:
/** @brief It doesn't
like this. */
// Renders properly:
/**
* @brief It does
*        like this.
*/
```
The other tweaks are just me preferring `/* Comment. */` for _inline comments_
and `// TODO: Something` for TODOs and `// someCode( 1 );` for _blocking out temporary code_.
That's just personal preference, you can use whichever you like.

docs: fixup docstrings and some comments

---

Makefile

Fixes a typo that causes OSX installs to fail.

fix: OSX install RPATH

---

include/flox/resolver/descriptor.hh
src/resolver/descriptor.cc

ManifestDescriptorRaw::optional is a std::optional<bool>, while ManifestDescriptor::optional is a bool, so constructing the bool from the std::optional<bool> incorrectly coerces an optional containing false to true. Instead, use value_or(false).

fix: buggy coercion to bool

---

include/flox/resolver/command.hh
include/flox/resolver/environment.hh
include/flox/resolver/lockfile.hh
include/flox/resolver/manifest-raw.hh
include/flox/resolver/manifest.hh
include/flox/resolver/mixins.hh
include/flox/search/command.hh
include/flox/search/params.hh
src/command.cc
src/main.cc
src/pkgdb/command.cc
src/pkgdb/get.cc
src/pkgdb/list.cc
src/pkgdb/scrape.cc
src/resolver/environment.cc
src/resolver/manifest-raw.cc
src/resolver/manifest.cc
src/resolver/mixins.cc
src/search/command.cc
src/search/params.cc
tests/search.bats

- move `[Global]ManifestRaw` to separate header
- move `EnvironmentMixin` to separate file
- path getters on `EnvironmentMixin`
- add `EnvironmentMixin::init<MEMBER>` from `<TYPE>Raw`
- make`manifest` field optional in `SearchParams`: `flox search '{ "query": { ... } }'`
- `SearchCommand::addSearchParamArgs`: `flox search --pname hello --version 4.2.0 ...;`
- fix: `to_json` for `SearchQuery`
- `EnvironmentMixin::addFloxDirectoryOption`: `flox search --dir ./.flox '{ "query": { ... } }';`
- `EnvironmentMixin::addGAManifestOption`: `flox search --ga-manifest '{ "query": { ... } }';`

feat: `flox search --ga-manifest` and other arg parser improvements

---

docs/visit.cc

Adds an example of creating _type safe_ `switch` case style statements for `std::variant` types.

doc: add example of std::visit for std::variants

---

include/flox/resolver/environment.hh
include/flox/resolver/lockfile.hh
include/flox/resolver/manifest.hh
src/resolver/environment.cc
src/resolver/lockfile.cc
src/resolver/manifest.cc
src/resolver/mixins.cc
tests/.gitignore
tests/environment.cc

- Drops `manifestPath` from `GlobalManifest` and `Manifest`.
- Drops `lockfilePath` from `Lockfile`.
These variables were frequently plugged with phony values, and weren't really required anywhere.

chore: drop `manifestPath` and `lockfilePath` member variables

---

include/flox/resolver/mixins.hh
src/resolver/mixins.cc
src/search/command.cc
tests/data/manifest/ga1.toml
tests/data/manifest/global-manifest0.toml

Don't pass the manifest as a global manifest. This also adds two test data files for manifests as they are handled today e.g. with the `--ga-registry` flag.

fix: don't pass manifest as global manifest

---

include/flox/core/util.hh
tests/registry.cc

This fixes a logic error in `merge_vectors` that causes registries to be duplicated and duplicate search results to be returned.

fix: logic error in merge_vectors

---

include/flox/resolver/environment.hh
src/resolver/environment.cc
tests/environment.cc

Split out some minor cleanup into the first commit.
The second commit implements the "Try to resolve X in the same revision, R, used by other members of group Y." part of the locking flowchart. There's definitely a lot of cases to consider, so I just picked behavior that makes sense for now - happy to revisit any of those choices now or in the future. In more detail...
When re-locking an environment, for each group, try to use the locked
input for the group present in the old lockfile. If resolution fails in
that input, continue to the other inputs in the environment's registry.
Choosing the locked input for a group is full of edge cases, because the
new group may be different than whatever was in the group in the old
lockfile. We still want to reuse old locked inputs when we can. For …

feat: use group's old locked input when possible

---

.github/workflows/test.yml
README.md
include/flox/registry.hh
include/flox/resolver/command.hh
include/flox/resolver/manifest-raw.hh
include/flox/resolver/mixins.hh
src/registry.cc
src/resolver/command.cc
src/resolver/environment.cc
src/resolver/manifest-raw.cc
src/resolver/mixins.cc
tests/data/manifest/global-manifest0.toml
tests/ga-registry.bats
tests/registry.cc
tests/setup_suite.bash

- Adds equality ops for Registry and conversions for manifest <--> GA types
- Adds `installFromJSON` helper
- Adds `_PKGDB_GA_REGISTRY_REF_OR_REV`
- Documents `--ga-registry`
- Adds `--ga-registry` support to `pkgdb manifest lock`
- Add `EnvionmentMixin::init[Global]Manifest` form paths
- Test cases for `--ga-registry`

feat: pkgdb manifest lock --ga-registry

---

.github/workflows/test.yml

Fixes: #139 
trusted-substituters does not mean used or activated

ci: Update test.yml to use substituters

---

flake.nix
include/flox/resolver/command.hh
include/flox/resolver/environment.hh
include/flox/resolver/lockfile.hh
include/flox/resolver/manifest-raw.hh
include/flox/resolver/mixins.hh
src/resolver/command.cc
src/resolver/environment.cc
src/resolver/lockfile.cc
src/resolver/mixins.cc
src/search/command.cc
src/util.cc
tests/environment.cc
tests/ga-registry.bats
tests/harnesses/proj1/manifest.lock
tests/harnesses/proj1/manifest.toml
tests/harnesses/proj1/manifest2.lock

- fixes: fix EnvironmentMixin::getLockfilePath and simplify EnvironmentMixinGA inits
- fixes: `Environment::getCombinedRegistry()` to include lockfile inputs.
- fixes: A bug which ignored the `options.systems` field in _manifest_ files in combination with `--ga-registry`.
- adds: `pkgdb manifest registry` sub-command
- adds: equality and ostream ops for lockfile inputs and packages
- adds: `pkgdb manifest update` sub-command
- `pkgdb manifest lock` should have special handling for inputs pulled from `global-manifest` which are not in `manifest.toml` if they are used to resolve packages ( warn the user ).

feat: 'pkgdb manifest {update,registry}' subcommands

---

src/nix-state.cc

Before this change, on a host with flakes disabled:
> ./bin/pkgdb manifest lock --ga-registry ~/debug/.flox/env/manifest.toml
error locking flake: failed to lock flake "github:NixOS/nixpkgs/release-23.05": error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
After:
> ./bin/pkgdb manifest lock --ga-registry ~/debug/.flox/env/manifest.toml
{...lockfile JSON...}

fix: enable flakes

---

include/flox/resolver/environment.hh
src/resolver/environment.cc

This deduplicates error messages encountered while trying to resolve a group of descriptors.

fix: no duplicate resolution error msgs

---

src/nix-state.cc

Forces the use of `experimental-features` and `use-eval-cache`.
Previously we only set fallbacks for these settings.
This should fix test case failures in `github:flox/flox`.

fix: assign nix settings

---

src/resolver/environment.cc

If an input from a lockfile is used to attempt to resolve, don't resolve a second time in the same input.

fix: don't resolve twice in the same input

---

docs/params-to-sql.md
include/flox/core/exceptions.hh
include/flox/pkgdb/pkg-query.hh
include/flox/search/params.hh
src/pkgdb/pkg-query.cc
src/search/params.cc
tests/pkgdb.cc

The `flox::pkgdb::PkgDescriptorBase` struct is no longer useful following
changes to search parameters and manifest descriptors.
This PR removes the struct and related docs.
The fields it provided to `PkgQueryArgs` and `SearchQuery` structs have been inlined there.
Ideally this should make the code-base slightly easier to read.

opt: remove PkgDescriptorBase

---

src/resolver/environment.cc

When locking an environment with an existing lockfile, packages that are already present in the lockfile are copied as is, ignoring any changes in the manifest file i.e. the `priority` field.
This change ensures that the `priority` field is updated even when the descriptor is copied.

fix: update `priority` field of existing descriptors

---

src/resolver/lockfile.cc

fix: probe if `system` is present before unwrapping

---

Makefile
flake.nix
src/resolver/environment.cc
tests/groups.bats
tests/harnesses/proj2/manifest.toml
tests/util.cc

- test: add new harness manifest and [lr]trim tests
- test: add tests for groups
- test: add note in about naive group implementation's limitations
There's an `XXX:` block for one test which is worth reviewing in detail.
It shows in practice what _naive implementation_ meant practically, and highlights one limitation that we would like to improve in the near future.

test: naive grouping strategy
